### PR TITLE
removed mutable reference to dispatch

### PR DESCRIPTION
**Pull request by TysonMN**
This is not directly related to issue https://github.com/elmish/Elmish.WPF/issues/331.  Just wanted to show you that you don't need a mutable reference to the `dispatch` function.

### CODE REVIEW

**Comment by Evangelink** [comment]
Thanks that's interesting, I will see if I can simplify the real app with this trick.

**Comment by Evangelink** [comment]
I couldn't find out how to make it work on my real app. Note that on my real app, I am one level down.

My `App.fs` has the following:

```fsharp
let main fwkElement =
    Program.mkProgramWpfWithCmdMsg init (update fwkElement) bindings bindCmd
    // Add a subscription to our analysis sub, mapping the message to an App level message
    |> Program.withSubscription (Analysis.AnalysisSub.sub >> Cmd.map AnalysisMsg)
    |> Program.startElmishLoop
        { ElmConfig.Default with
            LogConsole = true
            Measure = true }
        fwkElement
```

and `Analysis.fs` is the class where I am doing the events registrations.

**Comment by TysonMN** [comment]
I am sure the same change is possible in your real app.  It is "just" getting the types to line up, but that means all the details matter.  If you can share a working example that includes this extra layer of indirection, then I will make the same change to that example.

**Comment by Evangelink** [comment]
@TysonMN You can find the [ElmishMultiLevelSub folder](https://github.com/Evangelink/Elmish.Wpf.Experiments/tree/main/ElmishMultiLevelSub) where you will see the multi-level modules which made me implement the mutable Sub type/module. I'd be happy to get your feedback on how to remove it and only have the `Cmd.ofSub`.

**Comment by TysonMN** [comment]
Sorry for the delay.  I just created PR #6 that makes the requested improvement.

**Pull request merged**
